version: '2'

services:
  server:
    image: svogt/jabylon:latest
    volumes:
      - ./home:/home
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
