version: '2'

services:
  server:
    image: svogt/jabylon:latest
    ports:
      - "8080:8080"
    volumes:
      - ./jabylon:/root/jabylon
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
